"""initial migration

Revision ID: 180a7888b3c0
Revises: 
Create Date: 2026-10-04 23:59:46.038241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180a7888b3c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('print_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('printer', sa.String(length=255), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.Column('paper', sa.String(length=20), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('color', sa.Boolean(), nullable=True),
    sa.Column('duplex', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_user_id'), ['user_id'], unique=False)

    op.create_table('print_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['print_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_item_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_item_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_item_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_item_status'))
        batch_op.drop_index(batch_op.f('ix_print_item_name'))
        batch_op.drop_index(batch_op.f('ix_print_item_job_id'))

    op.drop_table('print_item')
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_print_job_created_at'))

    op.drop_table('print_job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
